#!/bin/bash


function readlink_rec {
	res="$(readlink $1 || echo $1)"
	if [ $res = $1 ]
	then
		echo $res
	else
		readlink_rec $res
	fi
}

root=`dirname "$(readlink_rec $0)"`
lib="$root/platform-turnus/target/lib"

comp="$root/platform-turnus/target/lib/compiler-1.0-SNAPSHOT.jar"
platforms="$root/platform-turnus/target/platform-multicore-1.0-SNAPSHOT.jar:$root/platform-turnus/target/platform-turnus-1.0-SNAPSHOT.jar"

if [ -f "$comp" ]
then
	java -cp "$comp:$platforms:$lib/*" se.lth.cs.tycho.compiler.Main "$@"
else
	echo "The project is not compiled. Please, run \"mvn install\" to compile."
	exit 1
fi
